version: "3.9"

services:
  postgresql:
    image: docker.io/bitnami/postgresql:15.1.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - "./postgres_data:/bitnami/postgresql"

  keycloak:
    image: bitnami/keycloak:20.0.1
    container_name: keycloak-themes-test
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: "true"
      KEYCLOAK_ADMIN_USER: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    ports:
      - 8888:8080
    volumes:
      - ./themes/:/opt/bitnami/keycloak/themes/
    depends_on:
      - postgresql
